// <auto-generated />
namespace IPL_TBS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class xyzac : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xyzac));
        
        string IMigrationMetadata.Id
        {
            get { return "202106230758118_xyzac"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
