// <auto-generated />
namespace IPL_TBS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202106230600214_Updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
